language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
# 0.6 appears to be unreliable on Travis at the moment.
#  - "0.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wput

after_success:
    "wput sjcl.js ftp://<put here username and password for ftp acount>@web303.78.cyhost.ch/sjcl.js"
